-- supabase/migrations/0001_create_tenants.sql

create table tenants (
  tenant_id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  name text not null,
  "responsibleParty" text not null,
  brn text,
  vat text,
  mobile text not null,
  address text
);

alter table tenants enable row level security;