create table
  public.orders (
    id text not null,
    created_at timestamptz default now() not null,
    tenant_id bigint not null,
    total numeric not null,
    vat numeric not null,
    subtotal numeric not null,
    cashier_id uuid null,
    constraint orders_pkey primary key (id),
    constraint orders_tenant_id_fkey foreign key (tenant_id) references tenants (tenant_id),
    constraint orders_cashier_id_fkey foreign key (cashier_id) references cashiers (id) on delete set null
  ) tablespace pg_default;

create table
  public.order_items (
    id bigint generated by default as identity,
    order_id text not null,
    product_id uuid not null,
    quantity integer not null,
    price numeric not null,
    constraint order_items_pkey primary key (id),
    constraint order_items_order_id_fkey foreign key (order_id) references orders (id) on delete cascade,
    constraint order_items_product_id_fkey foreign key (product_id) references products (id) on delete restrict
  ) tablespace pg_default;
