create table order_items (
    id bigint primary key generated by default as identity,
    order_id text not null,
    product_id uuid not null,
    quantity integer not null,
    price numeric not null,
    constraint fk_order
        foreign key(order_id)
        references orders(id)
        on delete cascade,
    constraint fk_product
        foreign key(product_id)
        references products(id)
        on delete restrict -- prevent deleting a product if it has been ordered
);

alter table order_items enable row level security;
